Corrected apcker hcl file , added iam profile to acces s3 bucket from base ami temprory insytance, roles are also temprary2

diff --git a/.github/workflows/major-deploy.yml b/.github/workflows/major-deploy.yml
--- a/.github/workflows/major-deploy.yml
+++ b/.github/workflows/major-deploy.yml
@@ -14,6 +14,11 @@ jobs:
   deploy-major:
     runs-on: ubuntu-latest
 
+    env:
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      AWS_DEFAULT_REGION: "us-east-1"
+
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -42,14 +47,13 @@ jobs:
           chmod 600 ~/packerkey.pem
           eval "$(ssh-agent -s)"
           ssh-add ~/packerkey.pem
-      
 
       - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v2
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: us-east-1  # Change if needed
+        run: |
+          export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
+          export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
+          export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
+          aws sts get-caller-identity || { echo "AWS authentication failed!"; exit 1; }
 
       - name: Verify WAR File
         working-directory: app-code
